package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.TianyuCourse;
import org.linlinjava.litemall.db.domain.TianyuCourseExample;

public interface TianyuCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course
     *
     * @mbg.generated
     */
    long countByExample(TianyuCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course
     *
     * @mbg.generated
     */
    int deleteByExample(TianyuCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course
     *
     * @mbg.generated
     */
    int insert(TianyuCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course
     *
     * @mbg.generated
     */
    int insertSelective(TianyuCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course
     *
     * @mbg.generated
     */
    TianyuCourse selectOneByExample(TianyuCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course
     *
     * @mbg.generated
     */
    TianyuCourse selectOneByExampleSelective(@Param("example") TianyuCourseExample example, @Param("selective") TianyuCourse.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course
     *
     * @mbg.generated
     */
    List<TianyuCourse> selectByExampleSelective(@Param("example") TianyuCourseExample example, @Param("selective") TianyuCourse.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course
     *
     * @mbg.generated
     */
    List<TianyuCourse> selectByExample(TianyuCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course
     *
     * @mbg.generated
     */
    TianyuCourse selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TianyuCourse.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course
     *
     * @mbg.generated
     */
    TianyuCourse selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course
     *
     * @mbg.generated
     */
    TianyuCourse selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TianyuCourse record, @Param("example") TianyuCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TianyuCourse record, @Param("example") TianyuCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TianyuCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TianyuCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") TianyuCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}