package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.TianyuCoursePlan;
import org.linlinjava.litemall.db.domain.TianyuCoursePlanExample;

public interface TianyuCoursePlanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course_plan
     *
     * @mbg.generated
     */
    long countByExample(TianyuCoursePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course_plan
     *
     * @mbg.generated
     */
    int deleteByExample(TianyuCoursePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course_plan
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course_plan
     *
     * @mbg.generated
     */
    int insert(TianyuCoursePlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course_plan
     *
     * @mbg.generated
     */
    int insertSelective(TianyuCoursePlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course_plan
     *
     * @mbg.generated
     */
    TianyuCoursePlan selectOneByExample(TianyuCoursePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course_plan
     *
     * @mbg.generated
     */
    TianyuCoursePlan selectOneByExampleSelective(@Param("example") TianyuCoursePlanExample example, @Param("selective") TianyuCoursePlan.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course_plan
     *
     * @mbg.generated
     */
    List<TianyuCoursePlan> selectByExampleSelective(@Param("example") TianyuCoursePlanExample example, @Param("selective") TianyuCoursePlan.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course_plan
     *
     * @mbg.generated
     */
    List<TianyuCoursePlan> selectByExample(TianyuCoursePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course_plan
     *
     * @mbg.generated
     */
    TianyuCoursePlan selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") TianyuCoursePlan.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course_plan
     *
     * @mbg.generated
     */
    TianyuCoursePlan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course_plan
     *
     * @mbg.generated
     */
    TianyuCoursePlan selectByPrimaryKeyWithLogicalDelete(@Param("id") Integer id, @Param("andLogicalDeleted") boolean andLogicalDeleted);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course_plan
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TianyuCoursePlan record, @Param("example") TianyuCoursePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course_plan
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TianyuCoursePlan record, @Param("example") TianyuCoursePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course_plan
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TianyuCoursePlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course_plan
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TianyuCoursePlan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course_plan
     *
     * @mbg.generated
     */
    int logicalDeleteByExample(@Param("example") TianyuCoursePlanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tianyu_course_plan
     *
     * @mbg.generated
     */
    int logicalDeleteByPrimaryKey(Integer id);
}